name: Build and Deploy

on:
  push:
    branches:
#      - dev
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set environment variables for branch
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          
          if [ "$BRANCH_NAME" = "main" ]; then
            echo "SSH_KEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.PROD_SSH_KEY }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "HOST=${{ vars.PROD_HOST }}" >> $GITHUB_ENV
            echo "TARGET_PATH=${{ vars.PROD_TARGET_PATH }}" >> $GITHUB_ENV
          else
            echo "SSH_KEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.DEV_SSH_KEY }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "HOST=${{ vars.DEV_HOST }}" >> $GITHUB_ENV
            echo "TARGET_PATH=${{ vars.DEV_TARGET_PATH }}" >> $GITHUB_ENV
          fi

          echo "USER=${{ vars.GIT_USER }}" >> $GITHUB_ENV

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.SSH_KEY }}

      - name: Disable host key checking
        run: |
          mkdir -p ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      - name: Copy .env from server
        run: |
          scp ${{ env.USER }}@${{ env.HOST }}:${{ env.TARGET_PATH }}/.env .env

      - name: Clean old dist and cache on server
        run: |
          ssh ${{ env.USER }}@${{ env.HOST }} "rm -rf ${{ env.TARGET_PATH }}/dist ${{ env.TARGET_PATH }}/.parcel-cache && mkdir -p ${{ env.TARGET_PATH }}/dist"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy new dist to server
        run: |
          rsync -avz ./dist/ ${{ env.USER }}@${{ env.HOST }}:${{ env.TARGET_PATH }}/dist
